version: '3'

services:
  app:
    ports:
      - 4000:3000
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    command: "npm run start:dev"
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: geneasur_db
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
